
import type { Metadata } from "next";
import { Poppins } from "next/font/google";

import "@/stylesheets/globals.css";
import ClientOnly from "@/components/ui/ClientOnly";
import Header from "@/components/Header/Header";

const poppins = Poppins({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
})

export const metadata: Metadata = {
  title: "Intapes",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className}`}>
        <ClientOnly>
          <Header />
          {children}
        </ClientOnly>
      </body>
    </html>
  );
}
